### ISSUE TITLE
error:unknown EbpfFuncName , couldn't find program at probe_entry_SSL_write

### ISSUE THREAD

**Issue by killdayu** [ehids/ecapture#105]
我在手机上使用了make nocore编译了它，但是在执行的时候遇到了问题。
![Screenshot_2022-06-22-03-34-34-03_9e8df3d0c7c1f50248b6ee043a653d26.jpg](https://user-images.githubusercontent.com/62084769/174883136-af5f4cdb-e37d-48d8-a575-1dc19b07eab7.jpg)

`# tmp ./ecapture tls --libssl="/apex/com.android.conscrypt/lib64/libssl.so" --pthread="/apex/com.android.runtime/lib64/bionic/libc.so" --hex
2022/06/21 19:29:52 pid info :13754
2022/06/21 19:29:52 start to run EBPFProbeOPENSSL module
2022/06/21 19:29:52 start to run EBPFProbeGNUTLS module
2022/06/21 19:29:52 lstat /etc/ld.so.conf: no such file or directory
2022/06/21 19:29:52 read file :/etc/ld.so.conf error .
2022/06/21 19:29:52 stat /usr/lib/libgnutls.so.30: no such file or directory
2022/06/21 19:29:52 start to run EBPFProbeNSPR module
2022/06/21 19:29:52 lstat /etc/ld.so.conf: no such file or directory
2022/06/21 19:29:52 read file :/etc/ld.so.conf error .
2022/06/21 19:29:52 HOOK type:2, binrayPath:/apex/com.android.conscrypt/lib64/libssl.so
2022/06/21 19:29:52 libPthread so Path:/apex/com.android.runtime/lib64/bionic/libc.so
2022/06/21 19:29:52 stat /usr/lib/libnspr4.so: no such file or directory
2022/06/21 19:29:52 couldn't init manager: error:unknown EbpfFuncName , couldn't find program at probe_entry_SSL_write`

- OS: [Android coloros v12]
- Arch: [arm_aarch64]
- Kernel Version: [4.19.125-perf+]
- Version: [v0.1.10]

**Comment by cfc4n** [comment]
大概是SSL.so里，符号表信息被去掉了，需要自己找偏移地址，再指定。
