### ISSUE TITLE
MIUI13 not support

### ISSUE THREAD

**Issue by MariShunxiang** [ehids/ecapture#110]
**Describe the bug**
```
1|cupid:/data/local/tmp/ecapture-v0.1.10-android_gki-aarch64 # ./ecapture                                                                                                                        
2022/06/25 04:54:19 BTF not support, please check it. shell: cat /boot/config-`uname -r` | grep CONFIG_DEBUG_INFO_BTF 
 You can compile a no BTF version by youeself with command `make nocore`,Please read Makefile for more info.
```

**Screenshots**

**Linux Server/Android (please complete the following information):**

- OS: [e.g. Ubuntu 21.04]
Linux localhost 5.10.43-android12-9-gb8e472053352-ab8059253 #1 SMP PREEMPT Mon Jan 10 06:58:42 UTC 2022 aarch64
 5.10.43-android12-9-gb8e472053352-ab8059253
- Arch: [e.g. arm_aarch64]
- Kernel Version: [e.g. 5.10]
- Version: [e.g. 0.1.3-20220313-69c1e0]

**Additional context**

**Comment by cfc4n** [comment]
Master branch is already supported.  I'll release version in the near future. 

or you can compile it by yourself.

If you can read Chinese,Join QQ Group, I'll send a new version.(群好吧在微信公众号里)
