### ISSUE TITLE
apple  m1 cannot  executed

### ISSUE THREAD

**Issue by huarong8** [ehids/ecapture#112]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Linux Server/Android (please complete the following information):**

- OS: [e.g. Ubuntu 21.04]
- Arch: [e.g. arm_aarch64]
- Kernel Version: [e.g. 5.10]
- Version: [e.g. 0.1.3-20220313-69c1e0]

**Additional context**

error: 
zsh: exec format error: ./ecapture

**Comment by cfc4n** [comment]
eCapture support Linux/Andorid  x86_64/Aarch64 only . do not support macOS.
