### ISSUE TITLE
Run cmd ./ecapture tls --hex, prompt TLS_VERSION_UNKNOWN

### ISSUE THREAD

**Issue by yakantosat** [ehids/ecapture#115]
Run the following cmd, prompt TLS_VERSION_UNKNOWN
 sudo ./ecapture tls --libssl="/lib/aarch64-linux-gnu/libssl.so.1.1" --gobin=/usr/local/go/bin/go --hex
![image](https://user-images.githubusercontent.com/2803714/176581029-8dc8103c-8212-40a6-8536-0c9b85396303.png)

System params:
- OS: Ubuntu server 20.04 LTS On Parallels Desktop 17 (macos with m1 chip)
- Arch: arm64
- Kernel Version: 5.4.0-121-generic

**Comment by huzai9527** [comment]
pls, make sure all .so paths are correct. 
I run the command below
```bash
./ecapture tls --libssl="/lib/aarch64-linux-gnu/libssl.so.1.1" --pthread="/lib/aarch64-linux-gnu/libpthread.so.0" --gobin=/usr/local/go/bin/go --gnutls="/lib/aarch64-linux-gnu/libgnutls.so.30" --nspr="/lib/aarch64-linux-gnu/libnspr4.so" --hex
```
and my system params:
```
Linux ubuntu-linux-20-04-desktop 5.13.0-51-generic
 #58~20.04.1-Ubuntu SMP Mon Jun 13 20:00:13 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
```
and use the latest ecapture.
finally I got the correct response
<img width="971" alt="image" src="https://user-images.githubusercontent.com/33509974/177306610-19b4697c-7036-4998-bc2b-3c8105f7db5c.png">
