### ISSUE TITLE
在谷歌手机下运行报错, 也无法抓到包

### ISSUE THREAD

**Issue by wolftail** [ehids/ecapture#122]
系统  Linux localhost 5.10.81-android12-9-00071-g64099431c232-ab8394429 #1 SMP PREEMPT Fri Apr 1 02:09:27 UTC 2022 aarch64

./ecapture tls --hex                                                             
tls_2022/07/05 10:03:28 pid info :18118
tls_2022/07/05 10:03:28 EBPFProbeOPENSSL	module initialization
tls_2022/07/05 10:03:28 EBPFProbeOPENSSL	module started successfully.
tls_2022/07/05 10:03:28 EBPFProbeGNUTLS	module initialization
tls_2022/07/05 10:03:28 EBPFProbeGNUTLS	module started successfully.
tls_2022/07/05 10:03:28 EBPFProbeNSPR	module initialization
tls_2022/07/05 10:03:28 EBPFProbeOPENSSL	Module.Run()
tls_2022/07/05 10:03:28 EBPFProbeOPENSSL	HOOK type:2, binrayPath:/apex/com.android.conscrypt/lib64/libssl.so
tls_2022/07/05 10:03:28 EBPFProbeOPENSSL	libPthread so Path:/apex/com.android.runtime/lib64/bionic/libc.so
tls_2022/07/05 10:03:28 EBPFProbeOPENSSL	target all process. 
tls_2022/07/05 10:03:28 EBPFProbeOPENSSL	target all users. 
tls_2022/07/05 10:03:28 EBPFProbeOPENSSL	module run failed, [skip it]. error:error:unknown EbpfFuncName , couldn't find program at probe_entry_SSL_write
couldn't init manager
ecapture/user.(*MOpenSSLProbe).start
	/source_code/user/probe_openssl.go:65
ecapture/user.(*MOpenSSLProbe).Start
	/source_code/user/probe_openssl.go:43
ecapture/user.(*Module).Run
	/source_code/user/imodule.go:92
ecapture/cli/cmd.openSSLCommandFunc.func1
	/source_code/cli/cmd/tls.go:119
runtime.goexit
	/usr/lib/go-1.18/src/runtime/asm_arm64.s:1259
tls_2022/07/05 10:03:28 EBPFProbeNSPR	module started successfully.
tls_2022/07/05 10:03:28 EBPFProbeGoSSL	module initialization
tls_2022/07/05 10:03:28 EBPFProbeGoSSL	module initialization failed. [skip it]. error:go binary not found
tls_2022/07/05 10:03:28 EBPFProbeNSPR	Module.Run()
tls_2022/07/05 10:03:28 EBPFProbeNSPR	module run failed, [skip it]. error:stat /apex/com.android.conscrypt/lib64/libnspr4.so: no such file or directory
tls module couldn't find binPath.
ecapture/user.(*MNsprProbe).start
	/source_code/user/probe_nspr.go:53
ecapture/user.(*MNsprProbe).Start
	/source_code/user/probe_nspr.go:36
ecapture/user.(*Module).Run
	/source_code/user/imodule.go:92
ecapture/cli/cmd.openSSLCommandFunc.func1
	/source_code/cli/cmd/tls.go:119
runtime.goexit
	/usr/lib/go-1.18/src/runtime/asm_arm64.s:1259
tls_2022/07/05 10:03:28 EBPFProbeGNUTLS	Module.Run()
tls_2022/07/05 10:03:28 EBPFProbeGNUTLS	module run failed, [skip it]. error:stat /apex/com.android.conscrypt/lib64/libgnutls: no such file or directory
tls(gnutls) module couldn't find binPath.
ecapture/user.(*MGnutlsProbe).start
	/source_code/user/probe_gnutls.go:53
ecapture/user.(*MGnutlsProbe).Start
	/source_code/user/probe_gnutls.go:36
ecapture/user.(*Module).Run
	/source_code/user/imodule.go:92
ecapture/cli/cmd.openSSLCommandFunc.func1
	/source_code/cli/cmd/tls.go:119
runtime.goexit
	/usr/lib/go-1.18/src/runtime/asm_arm64.s:1259

**Comment by cfc4n** [comment]
这个是 gnutls、nspr两个库的链接库没找到，不能运行。 但openssl的库成功运行了。 可以忽略，这个提示不友好，下个版本修复。

**Comment by cfc4n** [comment]
I'll release a new version . but I dont have Android device to Test, Can you help me ?

(加一下QQ群，帮测试一下内测版本哈，群二维码在公众号内)
