### ISSUE TITLE
make failed 

### ISSUE THREAD

**Issue by MythRen** [ehids/ecapture#144]
**Describe the bug**

**To Reproduce**
1. Go to the root directory of eCapture then run `make`

**Expected behavior**
make can compile the .c to .o success

**Screenshots**
![image](https://user-images.githubusercontent.com/5511286/180696907-0a926793-3b4a-4a76-9e56-c4df55021161.png)

**Linux Server/Android (please complete the following information):**

- OS: CentOS Linux release 8.2.2004 (Core)
- Arch: x86_64
- Kernel Version: 4.18.0-193.el8.x86_64
- Version: 0.3.0
- BTF enabled: yes
- go version: go version go1.18.4 linux/amd64

**Additional context**
no

**Comment by MythRen** [comment]
this is the vmlinux.h generated at my dev machine. 

[vmlinux.h.txt](https://github.com/ehids/ecapture/files/9178420/vmlinux.h.txt)

**Comment by cfc4n** [comment]
upload result  here used command`make env`.

**Comment by MythRen** [comment]
```
---------------------------------------
Makefile Environment:
---------------------------------------
PARALLEL                 32
---------------------------------------
CLANG_VERSION            10
GO_VERSION               1.18
---------------------------------------
CMD_CLANG                clang
CMD_GIT                  git
CMD_GO                   go
CMD_INSTALL              install
CMD_LLC                  llc
CMD_MD5                  md5sum
CMD_PKGCONFIG            pkg-config
CMD_STRIP                llvm-strip
VERSION                  -20220504-1cb258a-prev--dirty
LAST_GIT_TAG             -20220504-1cb258a-prev--dirty
TAG_COMMIT
TAG
COMMIT                   1cb258a
BPF_NOCORE_TAG           4_18_0-193_el8_x86_64.-20220504-1cb258a-prev--dirty
---------------------------------------
UNAME_M                  x86_64
UNAME_R                  4.18.0-193.el8.x86_64
ARCH                     x86_64
LINUX_ARCH               x86
---------------------------------------
KERN_RELEASE             4.18.0-193.el8.x86_64
KERN_BUILD_PATH          /lib/modules/4.18.0-193.el8.x86_64/build
KERN_SRC_PATH            /lib/modules/4.18.0-193.el8.x86_64/source
---------------------------------------
GO_ARCH                  amd64
---------------------------------------
```

**Comment by chriskaliX** [comment]
would you mind try to make it by clang-12? Thanks!
You can also get the QR of our QQ group by following the account https://github.com/ehids/ecapture/blob/master/images/wechat_gzhh.png for better communication

**Comment by MythRen** [comment]
update the clang to version 12, but also the same problem. 
BTW, i'm entering the QQ Group. :)))))

**Comment by chriskaliX** [comment]
This problem seems related with `bpftool` version since it is fixed when we use the proper `vmlinux.h`. Would you please upload the result of `$ bpftool version`, use latest bpftool and retry, see if the `vmlinux.h` is correct.

**Comment by chriskaliX** [comment]
The problem is related with `bpftool`. Feel free to reopen this issue or reach me by QQ if there is any doubt with it.
