### ISSUE TITLE
i can't compile this project,

### ISSUE THREAD

**Issue by RyanCode** [ehids/ecapture#146]
```
isContainer, err := ebpf.IsContainer()
var searchPath = GetDynLibDirs()
......
ui.Domainname = charsToString(u.Domainname)
```
u.Domainname undefined (type "golang.org/x/sys/unix".Utsname has no field or method Domainname)

mac os big sur 11.6.4

**Comment by cfc4n** [comment]
eCapture do not support macOS due macOS do not support eBPF.
