### ISSUE TITLE
支持macOS吗 嘿嘿

### ISSUE THREAD

**Issue by o2e** [ehids/ecapture#16]
macOS 10.15.7
Intel CPU 
编译不过如图， 不太了解go，折腾一顿没成功求助~
![image](https://user-images.githubusercontent.com/24642961/160531343-35a0eb9d-744d-47fc-9189-564c6870ed61.png)
![image](https://user-images.githubusercontent.com/24642961/160531368-a08e4fd3-6d4e-43a2-ba66-9cccddcfab21.png)

**Comment by yihong0618** [comment]
macOS 不支持的，因为目前 eBPF 只在内核版本相对较新的 Linux 上能跑

**Comment by cfc4n** [comment]
> macOS 不支持的，因为目前 eBPF 只在内核版本相对较新的 Linux 上能跑

是的，macOS不支持eBPF，现在只能在linux上运行，以后或许可以改到windows上。
