### ISSUE TITLE
How to compile the Android version?

### ISSUE THREAD

**Issue by backahasten** [ehids/ecapture#167]
您在readme中介绍了linux的编译方法，请问针对安卓设备应该如何编译呢？
You introduced the compilation method of Linux in readme. How should I compile for Android devices?

**Comment by SeeFlowerX** [comment]
check https://blog.seeflower.dev/archives/172/

**Comment by cfc4n** [comment]
也可以在ARM架构的linux服务器上编译，命令是 `ANDROID=1 make` 编译co:re 版本的，或者`ANDROID=1 make nocore`编译无co:re版本的。
