### ISSUE TITLE
capture to firefox content is encrypted

### ISSUE THREAD

**Issue by GitHubAmos** [ehids/ecapture#17]
**Describe the bug**
capture to firefox content is encrypted

**To Reproduce**
1. sudo ./ecapture tls --nspr /usr/lib/firefox/libnspr4.so
2. request https://www.baidu.com/robots.txt by firefox

**Screenshots**
ecapture output content(show a little part):
![image](https://user-images.githubusercontent.com/40637045/160609344-c1ccd9fe-ee70-4576-a77f-7a88434499a3.png)

**Linux Server/Desktop (please complete the following information):**
 - OS: Linux Desktop VM
 - Kernel Version 5.13.0-37-generic
 - Version 20.04.1-Ubuntu
 - Architecture x86_64 x86_64 x86_64 GNU/Linux

**Comment by cfc4n** [comment]
>Content-Encoding: gzip

eh... just compressed by gzip .   and you can read text context as `http request` and `http response header`. 

It is encoded, not encrypt.  and will fix it with #5

**Comment by GitHubAmos** [comment]
sorry，this is misjudgement！！！
thank you for your reply.
