### ISSUE TITLE
抓取pcap包还是tls加密

### ISSUE THREAD

**Issue by badboycxcc** [ehids/ecapture#172]
执行命令   
![image](https://user-images.githubusercontent.com/72059221/184604216-320df256-58f6-486f-ba3e-367312bf4908.png)

wireshark 查看  
![image](https://user-images.githubusercontent.com/72059221/184604397-8b630620-4f07-4bc4-be22-6f39264a710d.png)

**Comment by cfc4n** [comment]
按照issue的模版提一个吧。  起码把关键信息补充一下，比如 内核版本，openssl版本等，以及重现步骤。

**Comment by zhangbo1882** [comment]
具体什么问题，没看懂呢 @badboycxcc

**Comment by badboycxcc** [comment]
这个问题可以关闭了，我重新提一个。
