### ISSUE TITLE
捕获的Pcapng数据还是加密数据，没能解密。

### ISSUE THREAD

**Issue by badboycxcc** [ehids/ecapture#174]
### bug 
捕获的Pcapng数据包还是tls加密数据，使用Wireshark未能查看明文数据，且ecapture_masterkey.log文件内容为空。

#### 捕获命令如下：  
```
./ecapture tls -i enp1s0 -w 1.pcapng -p 443
```
![image](https://user-images.githubusercontent.com/72059221/184604216-320df256-58f6-486f-ba3e-367312bf4908.png)

#### wireshark查看内容  
![image](https://user-images.githubusercontent.com/72059221/184604397-8b630620-4f07-4bc4-be22-6f39264a710d.png)

### 系统版本如下：  
- OS: 20.04
- Arch: amd64
- Kernel Version: 5.4.0-113-generic
- Version: Ubuntu 20.04.3 LTS
- OpenSSL：1.1.1f  31 Mar 2020

**Comment by cfc4n** [comment]
openssl版本是多少？

**Comment by cfc4n** [comment]
--libssl参数指定一下路径
