### ISSUE TITLE
release nocore version

### ISSUE THREAD

**Issue by gitlsl** [ehids/ecapture#182]
android root 手机没有开bps的, 是不是用 nocore 编译的就行了呢, 可否在发布的时候也带上一个

**Comment by cfc4n** [comment]
`nocore`版本不是通用的，跟编译环境内核版本有关，我编译出来的，你手机上不一定能运行。

其次，现在自动构建是GitHub workflows做的，不支持ARM环境，目前使用qemu模拟的，类库缺失，无法编译。
