### ISSUE TITLE
ecapture tls start error on CentOS with kernel 5.6 BTF enabled

### ISSUE THREAD

**Issue by garyhuang123** [ehids/ecapture#190]
[root@localhost ecapture-v0.4.1-linux-x86_64]# ./ecapture  tls
tls_2022/09/04 18:45:13 ECAPTURE :: version :linux_x86_64:0.4.1-20220822-c6ff9aa:[CORE]
tls_2022/09/04 18:45:13 ECAPTURE :: pid info :21001
2022/09/04 18:45:13 read keylogger :ld.so.conf.d/*.conf error .
2022/09/04 18:45:13 read keylogger :ld.so.conf.d/*.conf error .
tls_2022/09/04 18:45:13 EBPFProbeOPENSSL	module initialization
tls_2022/09/04 18:45:13 EBPFProbeOPENSSL	master key keylogger: ecapture_masterkey.log
tls_2022/09/04 18:45:13 EBPFProbeOPENSSL	Module.Run()
tls_2022/09/04 18:45:13 EBPFProbeOPENSSL	UPROBE MODEL
tls_2022/09/04 18:45:13 EBPFProbeOPENSSL	HOOK type:2, binrayPath:/usr/lib64/libssl.so.10
tls_2022/09/04 18:45:13 EBPFProbeOPENSSL	libPthread so Path:/lib/libpthread.so.0
tls_2022/09/04 18:45:13 EBPFProbeOPENSSL	target all process. 
tls_2022/09/04 18:45:13 EBPFProbeOPENSSL	target all users. 
tls_2022/09/04 18:45:13 EBPFProbeOPENSSL	module run failed, [skip it]. error:couldn't init manager error:program probe_connect: apply CO-RE relocations: can't read types: type id 4801: unknown kind: Unknown (19) , couldn't load eBPF programs, cs:&{map[.rodata:Array(keySize=4, valueSize=32, maxEntries=1, flags=128) active_ssl_read_args_map:Hash(keySize=8, valueSize=16, maxEntries=1024, flags=0) active_ssl_write_args_map:Hash(keySize=8, valueSize=16, maxEntries=1024, flags=0) bpf_context:LRUHash(keySize=8, valueSize=408, maxEntries=2048, flags=0) bpf_context_gen:Array(keySize=4, valueSize=408, maxEntries=1, flags=0) connect_events:PerfEventArray(keySize=0, valueSize=0, maxEntries=0, flags=0) data_buffer_heap:PerCPUArray(keySize=4, valueSize=4152, maxEntries=1, flags=0) mastersecret_events:PerfEventArray(keySize=0, valueSize=0, maxEntries=0, flags=0) skb_data_buffer_heap:PerCPUArray(keySize=4, valueSize=40, maxEntries=1, flags=0) skb_events:PerfEventArray(keySize=0, valueSize=0, maxEntries=16, flags=0) tls_events:PerfEventArray(keySize=0, valueSize=0, maxEntries=0, flags=0)] map[egress_cls_func:0xc0001683c0 ingress_cls_func:0xc000169a40 probe_connect:0xc000169b80 probe_entry_SSL_read:0xc000168500 probe_entry_SSL_write:0xc000169ae0 probe_ret_SSL_read:0xc0001685a0 probe_ret_SSL_write:0xc000168460 probe_ssl_master_key:0xc000168320] 0xc0002a3b60 LittleEndian}
2022/09/04 18:45:13 read keylogger :ld.so.conf.d/*.conf error .
tls_2022/09/04 18:45:13 EBPFProbeGNUTLS	module initialization failed. [skip it]. error:stat /usr/lib/libgnutls.so.30: no such file or directory
tls_2022/09/04 18:45:13 EBPFProbeNSPR	module initialization failed. [skip it]. error:stat /usr/lib/libnspr4.so: no such file or directory
tls_2022/09/04 18:45:13 EBPFProbeGoSSL	module [disabled].
tls_2022/09/04 18:45:13 ECAPTURE :: 	No runnable modules, Exit(1)
[root@localhost ecapture-v0.4.1-linux-x86_64]# 

@cfc4n cfc4n

**Comment by chriskaliX** [comment]
I will look into this

**Comment by chriskaliX** [comment]
would you please post the result of `make env`

**Comment by garyhuang123** [comment]
hey @chriskaliX , i didn't compile ecapture myself, just used the release binary provided by ecapture github

**Comment by garyhuang123** [comment]
@chriskaliX, though, the result is
[root@localhost ecapture]# make env
fatal: unknown date format format:%Y%m%d
---------------------------------------
eCapture Makefile Environment:
---------------------------------------
PARALLEL                 16
---------------------------------------
CLANG_VERSION            
GO_VERSION               1.12
---------------------------------------
CMD_CLANG                clang
CMD_GIT                  git
CMD_GO                   go
CMD_INSTALL              install
CMD_LLC                  llc
CMD_MD5                  md5sum
CMD_PKGCONFIG            pkg-config
CMD_STRIP                llvm-strip
VERSION                  0.4.1--5f1b2ce
LAST_GIT_TAG             0.4.1--5f1b2ce
BPF_NOCORE_TAG           5_6_14-100_el7_x86_64.0_4_1--5f1b2ce
---------------------------------------
UNAME_M                  x86_64
UNAME_R                  5.6.14-100.el7.x86_64
ARCH                     x86_64
LINUX_ARCH               x86
---------------------------------------
KERN_RELEASE             5.6.14-100.el7.x86_64
KERN_BUILD_PATH          /lib/modules/5.6.14-100.el7.x86_64/build
KERN_SRC_PATH            /lib/modules/5.6.14-100.el7.x86_64/source
---------------------------------------
GO_ARCH                  amd64
ANDROID                  
AUTOGENCMD               bpftool btf dump file /sys/kernel/btf/vmlinux format c > kern/bpf/x86/vmlinux.h

**Comment by chriskaliX** [comment]
I've sent my wechat to your email, we can communicate over wechat for convenience :-)

**Comment by chriskaliX** [comment]
I think I just figure this out:
1. According to the error, it's in `cilium/ebpf` which is used in `ehids/ebpfmanager`
2. Dive into `cilium/ebpf`，we can see the stack like this: `LoadKernelSpec`-> `loadRawSpec` -> `parseBTF` -> `readTypes`（where the error occurs）. For now, `cilium/ebpf` only supports Kind 1 to 18(which is kindTypeTag), and
BTF_KIND_ENUM64 is not supported for now, but clearly it's coming
https://github.com/cilium/ebpf/issues/780
and you can see ENUM64 by `bpftool btf dump file /sys/kernel/btf/vmlinux | grep 4801`
3. We can see that in function `LoadKernelSpec`, cilium uses `/sys/kernel/btf/vmlinux` as defaults to load the spec, that's why in some particular case like this, the program throw an error even if there is not ENUM64 in eCapture

**How to fix this**
1. For now, we could only waiting for the support of `cilium/ebpf`, and we'll update.
2. Or you can use ubuntu 21.04 or some other distro instead of compiling the kernel which may include ENUM64

Feel free to reopen the issue if there is any questions.

**Comment by garyhuang123** [comment]
Thanks @chriskaliX !
