### ISSUE TITLE
服务端开启ecapture，无法抓到https流量

### ISSUE THREAD

**Issue by fengxuangit** [ehids/ecapture#191]
我想达到的效果就是，有人来请求服务端的https服务，我可以看到服务端返回给客户端的明文。

**Comment by blaisewang** [comment]
eCapture 启动时需要使用 --libssl 指定 HTTPS 服务使用的 SSL lib 路径

**Comment by fengxuangit** [comment]
<img width="738" alt="image" src="https://user-images.githubusercontent.com/9276329/188416993-3c1a01d2-fbcd-491d-a188-11eb6466ff42.png"> 
你好，我使用的是nginx，并在这个容器基础上搭建了一个https的网站可以正常访问，我在服务器上没有发现哪里是使用了libssl, 可以指点一下是如何查看https服务使用的ssl lib路径吗

**Comment by blaisewang** [comment]
看你 ldd 的结果，如果 nginx 还能提供 https 服务，那就是静态编译的 ssl lib？比较好处理的方法就是换成动态编译 openssl 的 nginx

**Comment by cfc4n** [comment]
libssl指定为nginx的路径试试。
libssl=`which nginx`

**Comment by fengxuangit** [comment]
> 

libssl=`which nginx` 这种方式不行

**Comment by fengxuangit** [comment]
> 

<img width="745" alt="企业微信截图_9d63310b-c362-4db5-bddb-4a20fdf5aa48" src="https://user-images.githubusercontent.com/9276329/188537847-8eb1d21f-b5b8-467a-bc70-caf541fcf385.png">

根据4楼的建议，动态编译Nginx 是可以抓到服务器端的流量的，解决问题，非常感谢。

**Comment by fengxuangit** [comment]
补充一下，测试了ecapture很多版本，最终是0.1.5这个版本才可以抓得到

**Comment by fengxuangit** [comment]
现在是能抓到流量了，但是抓到的是密文，不是明文。
<img width="510" alt="image" src="https://user-images.githubusercontent.com/9276329/188542973-c3f8a53a-19e6-475c-a87f-3d37d9fe431a.png">

**Comment by cfc4n** [comment]
你这是gzip压缩的，不是https加密的

**Comment by fengxuangit** [comment]
> 已解密了，你这是gzip压缩的，不是https加密的

非常感谢
