### ISSUE TITLE
for allcontributors Bot

### ISSUE THREAD

**Issue by cfc4n** [ehids/ecapture#195]
via : https://github.com/all-contributors/all-contributors/blob/master/README.md

**Comment by cfc4n** [comment]
@all-contributors please add @cfc4n  for infrastructure, tests and code

**Comment by cfc4n** [comment]
@all-contributors please add @chenhengqi @chriskaliX @cuishuang @4ft35t @vincentmli @tiann @yihong0618 @huzai9527 @nfsec  @blaisewang  for infrastructure, tests and code

**Comment by cfc4n** [comment]
https://github.com/all-contributors please add @chriskaliX for code

**Comment by cfc4n** [comment]
@all-contributors please add @cuishuang  for code

**Comment by cfc4n** [comment]
@all-contributors please add @4ft35t  for code

**Comment by cfc4n** [comment]
@all-contributors please add @vincentmli  for code

**Comment by cfc4n** [comment]
@all-contributors please add @tiann  for code

**Comment by cfc4n** [comment]
@all-contributors please add @yihong0618 for code

**Comment by cfc4n** [comment]
@all-contributors please add @huzai9527  for code

**Comment by cfc4n** [comment]
@all-contributors please add @nfsec  for code

**Comment by cfc4n** [comment]
@all-contributors please add @blaisewang for code

**Comment by cfc4n** [comment]
@all-contributors please add @chenhengqi  for code

**Comment by cfc4n** [comment]
@all-contributors please add @chriskaliX for code

**Comment by cfc4n** [comment]
@all-contributors please add @yindex  for code

**Comment by cfc4n** [comment]
@all-contributors please add @xujiajiadexiaokeai  for code

**Comment by cuishuang** [comment]
Thanks
