### ISSUE TITLE
CentOS 7.9 不支持，no BTF found for kernel version 5.16.14-1.el7.elrepo.x86_64: not supported

### ISSUE THREAD

**Issue by 10467106** [ehids/ecapture#2]
[root@localhost ecapture]# go run main.go 
2022/03/16 14:00:49 https://github.com/ehids/ecapture
2022/03/16 14:00:49 eBPF技术实现的无CA证书HTTPS抓包工具
2022/03/16 14:00:49 process pid: 3253
2022/03/16 14:00:49 start to run EBPFProbeBash module
2022/03/16 14:00:49 start to run EBPFProbeSSLDump module
2022/03/16 14:00:49 couldn't init manager: error:program probe_entry_SSL_write: CO-RE relocations: no BTF found for kernel version 5.16.14-1.el7.elrepo.x86_64: not supported , couldn't load eBPF programs, cs:&{map[active_ssl_read_args_map:Hash(keySize=8, valueSize=8, maxEntries=1024, flags=0) active_ssl_write_args_map:Hash(keySize=8, valueSize=8, maxEntries=1024, flags=0) data_buffer_heap:PerCPUArray(keySize=4, valueSize=4032, maxEntries=1, flags=0) tls_events:PerfEventArray(keySize=0, valueSize=0, maxEntries=0, flags=0)] map[probe_entry_SSL_read:0xc000086e60 probe_entry_SSL_write:0xc000086d20 probe_ret_SSL_read:0xc000086f00 probe_ret_SSL_write:0xc000086dc0] LittleEndian}
exit status 1

**Comment by cfc4n** [comment]
只支持 Linux kernel 5.08以上的内核 。   centos的8.5 也不过是4.18内核，不支持BTF。

**Comment by 10467106** [comment]
已经用 ELRepo 源升级到 5.16.14 内核了。

**Comment by SenberHu** [comment]
![image](https://user-images.githubusercontent.com/22938050/158537964-172dd0a6-723e-4cef-8a95-ea3513a4ba6a.png)
高版本内核也要开启btf才能用。
