### ISSUE TITLE
关于ssh的捕获

### ISSUE THREAD

**Issue by GitHubAmos** [ehids/ecapture#20]
**描述**
目前tsl HOOK是否支持ssh加密库的处理？
**ssh相关信息**
* 版本
  `OpenSSH_8.2p1 Ubuntu-4ubuntu0.4, OpenSSL 1.1.1f  31 Mar 2020`
* 动态库
  ![image](https://user-images.githubusercontent.com/40637045/160734281-b97da2aa-1b74-4762-946e-716e45fd9545.png)

**系统环境**
* OS: `Linux ubuntu`
* Kernel Version: `5.13.0-37-generic`
* Version: `20.04.1-Ubuntu`
* Architecture: `x86_64 x86_64 x86_64 GNU/Linux`

**Comment by cfc4n** [comment]
我看了下， 我的环境是ubuntu 21.04 ， SSHD是使用了OPENSSL的1.1.0类库，是静态编译的，符号表也被去除了。需要你自己用IDA Pro之类工具来定位一下SSL_Write\SSL_Read 两个函数的偏移地址offset，再手动指定到 eCapture参数里。  

理论上是可以捕获的。

**Comment by sun363587351** [comment]
> 我看了下， 我的环境是ubuntu 21.04 ， SSHD是使用了OPENSSL的1.1.0类库，是静态编译的，符号表也被去除了。需要你自己用IDA Pro之类工具来定位一下SSL_Write\SSL_Read 两个函数的偏移地址offset，再手动指定到 eCapture参数里。
> 
> 理论上是可以捕获的。

是否有CentOS8中解密SSH的方式，你是怎么查看sshd是否是使用了openssl类库？

**Comment by cfc4n** [comment]
看下我以前发的视频你吧。   `ldd` 看动态链接库，或者ida静态分析。

**Comment by sun363587351** [comment]
> 看下我以前发的视频吧。 `ldd` 看动态链接库，或者ida静态分析。

看过了，只是sshd 通过ldd好像没发现上述提到的两个函数

**Comment by xfliu2665** [comment]
> 我看了下， 我的环境是ubuntu 21.04 ， SSHD是使用了OPENSSL的1.1.0类库，是静态编译的，符号表也被去除了。需要你自己用IDA Pro之类工具来定位一下SSL_Write\SSL_Read 两个函数的偏移地址offset，再手动指定到 eCapture参数里。
> 
> 理论上是可以捕获的。

这个有操作指导吗？
1. 我好像在ecapture没有找到关于指定函数地址offset的参数
2. 如何通过工具找到函数的地址offset
感谢

**Comment by cfc4n** [comment]
> > 我看了下， 我的环境是ubuntu 21.04 ， SSHD是使用了OPENSSL的1.1.0类库，是静态编译的，符号表也被去除了。需要你自己用IDA Pro之类工具来定位一下SSL_Write\SSL_Read 两个函数的偏移地址offset，再手动指定到 eCapture参数里。
> > 理论上是可以捕获的。
> 
> 这个有操作指导吗？
> 
> 1. 我好像在ecapture没有找到关于指定函数地址offset的参数
> 2. 如何通过工具找到函数的地址offset
>    感谢

常见的静态分析知识，使用类似[ IDA ](https://hex-rays.com/ida-pro)之类反编译工具，可以搜索一下。
