### ISSUE TITLE
是否考虑支持ARM架构的发布版本

### ISSUE THREAD

**Issue by allinu** [ehids/ecapture#21]
现在项目发布的二进制文件无法在 Apple M1 上运行，猜测不是 arm 架构的，能否直接提供编译的 arm 版，这样也省去了反复编译的问题

🙏 感谢您的项目

**Comment by cfc4n** [comment]
arm架构的linux 是可以考虑的。但不支持macOS系统。

**Comment by allinu** [comment]
好的，谢谢 🙏
