### ISSUE TITLE
Can eCapture support  packet filter ?

### ISSUE THREAD

**Issue by zhangbo1882** [ehids/ecapture#210]
Can eCapture support packet filter such as src/dst IP filter ?

**Comment by cfc4n** [comment]
maybe will.  but not now .

**Comment by zhangbo1882** [comment]
For example, I only want to decrypt the traffic between 1.1.1.1 to 2.2.2.2. 
But we have to capture all master secrets for all TLS traffic.  The key size may be much larger than the traffic between 1.1.1.1 to 2.2.2.2.  In our production env, the key size can be up to GB while the traffic I want to decrypt is only several MB.

**Comment by blaisewang** [comment]
In `openssl_tc.h`, you can get `iph` as an [`iphdr`](https://github.com/spotify/linux/blob/master/include/linux/ip.h#L85) struct pointer, which contains src and dest IP info you need to filter. 

You can add filter logical by IP after [line 106 in openssl_tc.h](https://github.com/ehids/ecapture/blob/master/kern/openssl_tc.h#L106)

Recompile the code, then you should be able to do want you want to achieve.

**Comment by zhangbo1882** [comment]
Do we have plan to support it officially ?

**Comment by cfc4n** [comment]
> Do we have plan to support it officially ?

yes, we will .
