### ISSUE TITLE
Can eCapture support stop automatically ?

### ISSUE THREAD

**Issue by zhangbo1882** [ehids/ecapture#211]
Can eCapture stop after sometime automatically ?

**Comment by cfc4n** [comment]
What is the use case for this issue?

**Comment by zhangbo1882** [comment]
If there are heavy traffic, the output will be huge.  We need a mechanism to stop for sometime or when file size is large.
Sometimes it is not difficult to stop it manually.

**Comment by cfc4n** [comment]
did `tcpdump` support this?

**Comment by zhangbo1882** [comment]
tcpdump can only support create multiple files per the time duration or file size. 
I think it is better to have this feature to stop automatically. You can check some packet capture tools developed by vendors,   all have such features. Actually, it is not difficult to have this feature, right ? :-)

**Comment by cfc4n** [comment]
eh... this ia a uncommon case.   you can edit it by yourself .
add a `timer, to send a signal to `stopper` chan at https://github.com/ehids/ecapture/blob/master/cli/cmd/tls.go#L56

**Comment by zhangbo1882** [comment]
I will try to add a PR.

**Comment by cfc4n** [comment]
> I will try to add a PR.

no..no...no ,  I think  eCapture do not need this feature.

**Comment by chriskaliX** [comment]
Maybe use `timeout <seconds> ./ecapture ...` for this case
