### ISSUE TITLE
module run failed, [skip it]. error:tls(gnutls) module couldn't find binPath stat /apex/com.android.conscrypt/lib64/libgnutls: no such file or directory

### ISSUE THREAD

**Issue by sonicman** [ehids/ecapture#213]
**Describe the bug**
1. module run failed, [skip it]. error:tls(gnutls) module couldn't find binPath stat /apex/com.android.conscrypt/lib64/libgnutls: no such file or directory
2.  when use ctrl + c to stop, my phone will panic.
--------------------------------
**PANIC
sReason: null_pointer
info: PC __sync_icache_dcache +0x34/0xf0**
-------------------------------- 

**To Reproduce**
when start captrue tls session on my phone，

**Screenshots**

 # ./ecapture tls --hex -d -p 25708                                                                                                                                             
2:00:47 ECAPTURE :: version :androidgki_aarch64:0.4.3-20220909-1edb73e:5.4.0-104-generic                                                                                        
2:00:47 ECAPTURE :: pid info :26810                                                                                                                                             
2:00:47 EBPFProbeOPENSSL        module initialization                                                                                                                           
2:00:47 EBPFProbeOPENSSL        master key keylogger: ecapture_masterkey.log                                                                                                    
2:00:47 EBPFProbeOPENSSL        Module.Run()                                                                                                                                    
2:00:47 EBPFProbeOPENSSL        UPROBE MODEL                                                                                                                                    
2:00:47 EBPFProbeOPENSSL        HOOK type:2, binrayPath:/apex/com.android.conscrypt/lib64/libssl.so                                                                             
2:00:47 EBPFProbeOPENSSL        libPthread so Path:/apex/com.android.runtime/lib64/bionic/libc.so                                                                               
2:00:47 EBPFProbeOPENSSL        target PID:25708                                                                                                                                
2:00:47 EBPFProbeOPENSSL        target all users.                                                                                                                               
2:00:47 EBPFProbeOPENSSL        module started successfully.                                                                                                                    
2:00:47 EBPFProbeGNUTLS module initialization                                                                                                                                   
2:00:47 EBPFProbeGNUTLS Module.Run()                                                                                                                                            
2:00:47 EBPFProbeGNUTLS module run failed, [skip it]. error:tls(gnutls) module couldn't find binPath stat /apex/com.android.conscrypt/lib64/libgnutls: no such file or directory
2:00:47 EBPFProbeNSPR   module initialization                                                                                                                                   
2:00:47 EBPFProbeNSPR   Module.Run()                                                                                                                                            
2:00:47 EBPFProbeNSPR   module run failed, [skip it]. error:tls module couldn't find binPath stat /apex/com.android.conscrypt/lib64/libnspr4.so: no such file or directory      
2:00:47 EBPFProbeGoSSL  module [disabled].                                                                                                                                      
2:00:47 ECAPTURE ::     start 1 modules                                                                                                                                         

**Android:**
# uname -r
5.10.110-qki-consolidate-android12-9-ga3375502e9ca

**Comment by asmoker** [comment]
my error msgs:

```bash
alioth:/data/local/tmp $ ./ecapture tls
tls_2022/09/14 06:27:00 ECAPTURE :: version :androidgki_aarch64:0.4.3-20220909-1edb73e:5.4.0-104-generic
tls_2022/09/14 06:27:00 ECAPTURE :: pid info :14119
tls_2022/09/14 06:27:00 EBPFProbeOPENSSL	module initialization
tls_2022/09/14 06:27:00 EBPFProbeOPENSSL	master key keylogger: ecapture_masterkey.log
tls_2022/09/14 06:27:00 EBPFProbeOPENSSL	Module.Run()
tls_2022/09/14 06:27:00 EBPFProbeOPENSSL	UPROBE MODEL
tls_2022/09/14 06:27:00 EBPFProbeOPENSSL	HOOK type:2, binrayPath:/apex/com.android.conscrypt/lib64/libssl.so
tls_2022/09/14 06:27:00 EBPFProbeOPENSSL	libPthread so Path:/apex/com.android.runtime/lib64/bionic/libc.so
tls_2022/09/14 06:27:00 EBPFProbeOPENSSL	module run failed, [skip it]. error:couldn't init manager error:operation not permitted , couldn't adjust RLIMIT_MEMLOCK
tls_2022/09/14 06:27:00 EBPFProbeGNUTLS	module initialization
tls_2022/09/14 06:27:00 EBPFProbeGNUTLS	Module.Run()
tls_2022/09/14 06:27:00 EBPFProbeGNUTLS	module run failed, [skip it]. error:tls(gnutls) module couldn't find binPath stat /apex/com.android.conscrypt/lib64/libgnutls: no such file or directory
tls_2022/09/14 06:27:00 EBPFProbeNSPR	module initialization
tls_2022/09/14 06:27:00 EBPFProbeNSPR	Module.Run()
tls_2022/09/14 06:27:00 EBPFProbeNSPR	module run failed, [skip it]. error:tls module couldn't find binPath stat /apex/com.android.conscrypt/lib64/libnspr4.so: no such file or directory
tls_2022/09/14 06:27:00 EBPFProbeGoSSL	module [disabled].
tls_2022/09/14 06:27:00 ECAPTURE :: 	No runnable modules, Exit(1)
```

---

uname -r

```bash
4.19.157-perf-g42d3bfdbbffc
```

**Comment by cfc4n** [comment]
> my error msgs:
> 
> ```shell
> alioth:/data/local/tmp $ ./ecapture tls
> tls_2022/09/14 06:27:00 ECAPTURE :: version :androidgki_aarch64:0.4.3-20220909-1edb73e:5.4.0-104-generic
> tls_2022/09/14 06:27:00 ECAPTURE :: pid info :14119
> tls_2022/09/14 06:27:00 EBPFProbeOPENSSL	module initialization
> tls_2022/09/14 06:27:00 EBPFProbeOPENSSL	master key keylogger: ecapture_masterkey.log
> tls_2022/09/14 06:27:00 EBPFProbeOPENSSL	Module.Run()
> tls_2022/09/14 06:27:00 EBPFProbeOPENSSL	UPROBE MODEL
> tls_2022/09/14 06:27:00 EBPFProbeOPENSSL	HOOK type:2, binrayPath:/apex/com.android.conscrypt/lib64/libssl.so
> tls_2022/09/14 06:27:00 EBPFProbeOPENSSL	libPthread so Path:/apex/com.android.runtime/lib64/bionic/libc.so
> tls_2022/09/14 06:27:00 EBPFProbeOPENSSL	module run failed, [skip it]. error:couldn't init manager error:operation not permitted , couldn't adjust RLIMIT_MEMLOCK
> tls_2022/09/14 06:27:00 EBPFProbeGNUTLS	module initialization
> tls_2022/09/14 06:27:00 EBPFProbeGNUTLS	Module.Run()
> tls_2022/09/14 06:27:00 EBPFProbeGNUTLS	module run failed, [skip it]. error:tls(gnutls) module couldn't find binPath stat /apex/com.android.conscrypt/lib64/libgnutls: no such file or directory
> tls_2022/09/14 06:27:00 EBPFProbeNSPR	module initialization
> tls_2022/09/14 06:27:00 EBPFProbeNSPR	Module.Run()
> tls_2022/09/14 06:27:00 EBPFProbeNSPR	module run failed, [skip it]. error:tls module couldn't find binPath stat /apex/com.android.conscrypt/lib64/libnspr4.so: no such file or directory
> tls_2022/09/14 06:27:00 EBPFProbeGoSSL	module [disabled].
> tls_2022/09/14 06:27:00 ECAPTURE :: 	No runnable modules, Exit(1)
> ```
> 
> uname -r
> 
> ```shell
> 4.19.157-perf-g42d3bfdbbffc
> ```
change to `root` user.

**Comment by asmoker** [comment]
> 

I got that:

```bash
alioth:/data/local/tmp $ su root
/system/bin/sh: su: inaccessible or not found
```

em...is that right?  🤔

**Comment by cfc4n** [comment]
> > 
> 
> I got that:
> 
> ```shell
> alioth:/data/local/tmp $ su root
> /system/bin/sh: su: inaccessible or not found
> ```
> 
> em...is that right? 🤔

use `su` to change to root on Android .

**Comment by cfc4n** [comment]
any question yet?
