### ISSUE TITLE
cannot capture data when used ebedtls

### ISSUE THREAD

**Issue by 10cks** [ehids/ecapture#218]
**Describe the bug**
ebedtls使用的类库与ecapture hook的相同，但是无法抓取。不知原因是什么。
**To Reproduce**

**Expected behavior**

**Screenshots**

**Linux Server/Android (please complete the following information):**

- Env: [run `make env` to get the environment variables]
- OS: [e.g. Ubuntu 21.04]
- Arch: [e.g. arm_aarch64]
- Kernel Version: [e.g. 5.10]
- Version: [e.g. 0.1.3-20220313-69c1e0]

**Additional context**

**Comment by blaisewang** [comment]
去 ebedtls 项目提交你的疑问更合适，另外建议提供详细的背景信息
