### ISSUE TITLE
明文抓包是否有问题

### ISSUE THREAD

**Issue by feymanpaper** [ehids/ecapture#219]
## 测试环境：
Ubuntu 20.0.4
ecapture版本0.4.3
## 描述
按照视频进行配置后，使用下列命令进行抓包
```
sudo ./ecapture tls --nspr /usr/lib/firefox/libnspr4.so
```
然后用firefox浏览器访问 https://www.baidu.com/robots.txt , 得到的截图如下：

![image](https://user-images.githubusercontent.com/94893978/192089766-1c7eb137-1b1e-4742-9402-20baa5fb20a5.png)

并且 --hex功能也有问题，无法得到robots.txt的正确内容

**Comment by cfc4n** [comment]
firefox有很多线程，会输出很多网络行为，不止是你访问的baidu，可以用-l参数保存到文件，再grep搜
