### ISSUE TITLE
masterkey文件为空 且包也没有解密

### ISSUE THREAD

**Issue by boost2020** [ehids/ecapture#221]
环境：
内核版本：Linux al-d1-wave-consul-test-0913-001 5.15.0-46-generic #49-Ubuntu SMP Thu Aug 4 18:03:25 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
编译条件： make nocore(阿里镜像默认没有开btf,所以无法使用make 默认编译）
ecapture版本： eCapture version:	linux_x86_64:0.4.3-20220916-d82a347:5.15.0-46-generic

问题描述：
使用以下命令抓https:
./ecapture  tls -i eth0 -w baidu.pcapng --port=443

输出的信息如下：
<img width="1398" alt="image" src="https://user-images.githubusercontent.com/62824352/192145291-0618d6fd-5d75-4324-ad8b-841d9f004208.png">

key文件为空：
<img width="739" alt="image" src="https://user-images.githubusercontent.com/62824352/192144967-e1f93e7d-4ce4-4363-aae8-de62ce459b75.png">
抓包的数据也是没有解密：
<img width="1390" alt="image" src="https://user-images.githubusercontent.com/62824352/192145164-f6c595fb-12d5-4f6f-b5c0-5a47f978d12a.png">

求大神解惑！

**Comment by cfc4n** [comment]
访问百度的程序，使用的类库 与  eCapture hook的ssl库是同一个吗？ 先确认。  另外，多读文章，了解使用方法。

**Comment by boost2020** [comment]
> 访问百度的程序，使用的类库 与 eCapture hook的ssl库是同一个吗？ 先确认。 另外，多读文章，了解使用方法。

![image](https://user-images.githubusercontent.com/62824352/192179063-e485a6c3-88b4-4bb2-a740-1ec8d0f5f602.png)

![image](https://user-images.githubusercontent.com/62824352/192179119-e13fb30c-ae86-47b0-95f3-c7f7404a32d0.png)

**Comment by cfc4n** [comment]
`libssl.so.3` 不是 openssl 1.1.x 系列的吧？  是 `openssl 3.0`分支的，暂时还没时间去适配。。

**Comment by cfc4n** [comment]
所以，先关了这个issue
