### ISSUE TITLE
 libnss3.so要使用哪个参数呢？

### ISSUE THREAD

**Issue by New-arkssac** [ehids/ecapture#227]
# libnss3.so要使用哪个参数呢？
ubuntu 22.04
想抓chromium的包
chromium的依赖/snap/chromium/2117/usr/lib/x86_64-linux-gnu/libnss3.so貌似无法使用参数去捕获
![image](https://user-images.githubusercontent.com/70094380/194012556-e9ee9f8f-1b47-4b41-94cd-0b937748c0be.png)

这是我找到的chrmium的依赖
![image](https://user-images.githubusercontent.com/70094380/194012800-4340f56c-e92a-4559-9a93-0d8aacc30610.png)

**Comment by cfc4n** [comment]
`objdump -T /snap/chromium/2117/usr/lib/x86_64-linux-gnu/libnss3.so |grep PR_Write`  看看有没有对应函数的符号。或者`--nspr` 参数指定到`/snap/chromium/2117/usr/lib/x86_64-linux-gnu/libnspr4.so` 试试。

**Comment by New-arkssac** [comment]
我尝试使用--nspr去指定/snap/chromium/2117/usr/lib/x86_64-linux-gnu/libnspr4.so，ecapture没有报错，但是并没有捕获chromium的数据

**Comment by New-arkssac** [comment]
我尝试使用--nspr去指定/snap/chromium/2117/usr/lib/x86_64-linux-gnu/libnspr4.so，ecapture没有报错，但是并没有捕获chromium的流量
![image](https://user-images.githubusercontent.com/70094380/194213534-cea6c92e-c3ee-4834-bb28-8a7cc9e445fb.png)

我也使用了objdump -T /snap/chromium/2117/usr/lib/x86_64-linux-gnu/libnss3.so |grep -E "PR_Write|PR_Read|PR_Send"去查看libnss3.so是否存在相关的函数符号

![image](https://user-images.githubusercontent.com/70094380/194213902-f9cb8531-dd5a-43bb-a3e3-733c2761be35.png)
它们都存在在libnss3.so的文件里

**Comment by chriskaliX** [comment]
I'll look into this

**Comment by New-arkssac** [comment]
I‘ll wait for you bro

**Comment by chriskaliX** [comment]
it seems that chromium uses [boringssl](https://github.com/chromium/chromium/blob/220bd0b463b92941e4b16b2264ae05d061d9601e/DEPS#L261), I need some time to look into this...

**Comment by chriskaliX** [comment]
如果我没理解错的话，chrome/chromium采用了boringssl，没有直接导出SSL_Write/Read，需要手动寻找，windows下有类似的[文章](https://nytrosecurity.com/2018/02/26/hooking-chromes-ssl-functions/)，我对这个不是很熟悉，需要花时间看一下。可以先用 firefox 的看一下

**Comment by SeeFlowerX** [comment]
安卓上也有人写过方案，可以看看

[自动定位webview中的SLL_read和SSL_write
](https://mabin004.github.io/2020/07/24/%E8%87%AA%E5%8A%A8%E5%AE%9A%E4%BD%8Dwebview%E4%B8%AD%E7%9A%84SLL-read%E5%92%8CSSL-write/)

**Comment by New-arkssac** [comment]
ok，我会尝试的
