### ISSUE TITLE
a function question

### ISSUE THREAD

**Issue by zstdadi** [ehids/ecapture#228]
Could eCapture capture text content(URL etc.) from socks(ss)/https proxy(squid) /openvpn(openssl based)/stunnel's traffic?

**Comment by cfc4n** [comment]
> Could eCapture capture text content(URL etc.) from socks(ss)/https proxy(squid) /openvpn(openssl based)/stunnel's traffic?

yes，It can.

**Comment by cfc4n** [comment]
> OS version ? kernel version? openvpn version ? etc....
> 
> ubuntu or centos
> 
> Kernel version > 4.15
> 
> openvpn 2.x
> 
> You can test in your env.
I'll test later.

ref #229

**Comment by cfc4n** [comment]
```shell
root@VM-16-7-ubuntu:~# which openvpn
/usr/sbin/openvpn
root@VM-16-7-ubuntu:~# ldd /usr/sbin/openvpn
	linux-vdso.so.1 (0x00007ffc8d9fd000)
	liblzo2.so.2 => /lib/x86_64-linux-gnu/liblzo2.so.2 (0x00007f67fba70000)
	liblz4.so.1 => /lib/x86_64-linux-gnu/liblz4.so.1 (0x00007f67fba4f000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f67fba2c000)
	libpkcs11-helper.so.1 => /lib/x86_64-linux-gnu/libpkcs11-helper.so.1 (0x00007f67fba0c000)
	libcrypto.so.1.1 => /lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f67fb736000)
	libssl.so.1.1 => /lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007f67fb6a3000)
	libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007f67fb5f2000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f67fb5ec000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f67fb3fa000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f67fbb6d000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f67fb3f0000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f67fb3c7000)
	libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007f67fb2a9000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f67fb284000)
root@VM-16-7-ubuntu:~# ldd /usr/sbin/openvpn |grep ssl
	libssl.so.1.1 => /lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007fb1e0f2b000)
```
openvpn used `/lib/x86_64-linux-gnu/libssl.so.1.1` as tls/ssl shared object lib. so ,eCapture can works.
@zstdadi

**Comment by zstdadi** [comment]
> ```shell
> root@VM-16-7-ubuntu:~# which openvpn
> /usr/sbin/openvpn
> root@VM-16-7-ubuntu:~# ldd /usr/sbin/openvpn
> 	linux-vdso.so.1 (0x00007ffc8d9fd000)
> 	liblzo2.so.2 => /lib/x86_64-linux-gnu/liblzo2.so.2 (0x00007f67fba70000)
> 	liblz4.so.1 => /lib/x86_64-linux-gnu/liblz4.so.1 (0x00007f67fba4f000)
> 	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f67fba2c000)
> 	libpkcs11-helper.so.1 => /lib/x86_64-linux-gnu/libpkcs11-helper.so.1 (0x00007f67fba0c000)
> 	libcrypto.so.1.1 => /lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f67fb736000)
> 	libssl.so.1.1 => /lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007f67fb6a3000)
> 	libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007f67fb5f2000)
> 	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f67fb5ec000)
> 	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f67fb3fa000)
> 	/lib64/ld-linux-x86-64.so.2 (0x00007f67fbb6d000)
> 	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f67fb3f0000)
> 	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f67fb3c7000)
> 	libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007f67fb2a9000)
> 	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f67fb284000)
> root@VM-16-7-ubuntu:~# ldd /usr/sbin/openvpn |grep ssl
> 	libssl.so.1.1 => /lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007fb1e0f2b000)
> ```
> 
> openvpn used `/lib/x86_64-linux-gnu/libssl.so.1.1` as tls/ssl shared object lib. so ,eCapture can works. @zstdadi

openvpn has linked to libssl.so, but when I run ecapture tls, no results display, while when I run curl/wget it has results display.

**Comment by cfc4n** [comment]
how do you run openvpn?   what is the client command and server command?

**Comment by zstdadi** [comment]
> how do you run openvpn? what is the client command and server command?
If a openvpn client connected to a server, it created a tun NIC, and add a route via tun NIC，when dest IP is in this route, the traffic will run via this tun NIC, I can ping such dest IP to test vpn route. No special CLi command program.

**Comment by cfc4n** [comment]
Setting up a runtime environment is particularly painful. I cannot finish.
