### ISSUE TITLE
running on the arm64 system , can not catch any data, specify --libssl, and then run the error as follows

### ISSUE THREAD

**Issue by Qiaijueqing** [ehids/ecapture#230]
closed

**Comment by cfc4n** [comment]
is `/apex/com.android.conscrypt/lib/libssl.so` a 32bit shared object file ? use x86_64/arm64 eCapture to attach 32bit shared object is not supported yet.

**Comment by cfc4n** [comment]
no plan now , maybe 1-2 years later .
