### ISSUE TITLE
Can eCapture support quic tls1.3

### ISSUE THREAD

**Issue by linsy007** [ehids/ecapture#233]
quic(xquic/lsquic) use boringssl or openssl 
   example: xquic+boringssl
expect eCapture can suport capture quic text content without CA
system: linux or android

**Comment by blaisewang** [comment]
Correct me if I'm wrong, OpenSSL hasn't had QUIC implementation yet. See https://www.openssl.org/blog/blog/2021/12/03/starting-the-quic-design/ and related issues mentioned in the post.

Both xquic and lsquic uses BoringSSL, and xquic support Tongsuo (formerly BabaSSL, an OpenSSL fork and enhancement).

Hooking BoringSSL seems to be a good option if we decide to support QUIC with TLSv1.3

**Comment by blaisewang** [comment]
QUIC is an underlay protocol and has multiple versions, like 35, 39, 43, 44, etc. Both HTTP/2 and HTTP/3 can run over QUIC, which needs two additional dissectors to decode the captured encoded raw bytes.

For now, you may try to run eCapture in openssl_tc mode, which will capture TLS stream with TLS session key stored. Then you can dissect the TLS stream with stored TLS session key with Wireshark, as Wireshark has multiple dissectors implemented.

**Comment by cfc4n** [comment]
ping...  @linsy007

**Comment by linsy007** [comment]
> Correct me if I'm wrong, OpenSSL hasn't had QUIC implementation yet. See https://www.openssl.org/blog/blog/2021/12/03/starting-the-quic-design/ and related issues mentioned in the post.
> 
> Both xquic and lsquic uses BoringSSL, and xquic support Tongsuo (formerly BabaSSL, an OpenSSL fork and enhancement).
> 
> Hooking BoringSSL seems to be a good start if we decide to support QUIC dissect with TLSv1.3

**Comment by linsy007** [comment]
> Correct me if I'm wrong, OpenSSL hasn't had QUIC implementation yet. See https://www.openssl.org/blog/blog/2021/12/03/starting-the-quic-design/ and related issues mentioned in the post.
> openssl has quic implementation, examples: ngtcp2
> Both xquic and lsquic uses BoringSSL, and xquic support Tongsuo (formerly BabaSSL, an OpenSSL fork and enhancement).
> 
> Hooking BoringSSL seems to be a good start if we decide to support QUIC dissect with TLSv1.3
   yes,can we prrferred support QUIC disect with TLSv1.3 ? example lsquic base BoringSSL

**Comment by linsy007** [comment]
> QUIC is an underlay protocol compare to HTTP which has multiple versions, like quic-35, quic-39, quic-43, quic-44, etc. Both HTTP/2 and HTTP/3 can run over QUIC protocol, which needs two additional dissectors to decode the captured encoded raw bytes.
> preferred implement http/3 over quic, rfc9000/rfc9114   http3 over quic already standard
> For now, you may try to run eCapture in openssl_tc mode, which will capture TLS stream with TLS session key stored. Then you can dissect the TLS stream with stored TLS session key in Wireshark, as Wireshark has multiple dissectors implemented.
-------QUIC support derive (pre)-master keys, but must reboot quic progress，if ecapture derive (pre)-master key without reboot progress, this is peffect

**Comment by linsy007** [comment]
> ping... @linsy007

reply

**Comment by blaisewang** [comment]
> ngtcp2

The backend of ngtcp2 is quictls, which is also a fork of OpenSSL, essentially not OpenSSL.
