### ISSUE TITLE
v0.4.5 nocore 版本无法顺利抓包及解密

### ISSUE THREAD

**Issue by bluegatar** [ehids/ecapture#235]
**Describe the bug**
4.5 nocore 版本无法顺利抓包及解密

操作adb命令OS:
kalinux2021

手机：
**pixel 6    v12    SQ1D.220205.004**
Kernel Version:  5.10.43-android12-9-00007-g9771767708df-ab8009062  Thu Dec 16 04:22:18 UTC 2021

运行 zcat /proc/config.gz | grep CONFIG_DEBUG_INFO_BTF
显示：
CONFIG_DEBUG_INFO_BTF not set

**过程**
全新root后的pixel运行4.5 nocore程序，均在开始时运行google play并抓包，而后用手机上的chorme浏览器浏览 《百度百科》任何一个百科：

1：用 ./ecapture tls 可以看到很多包产生持续很长时间（但绝大多数是google的包），抓包界面无显示有baidu的包；

2：用./ecapture tls -i wlan0 -w 11.pcapng 可以保存pcapng 查看，pull到电脑上用wireshark（最新版）查看，所有的包（google play和百度百科）均未解密，无法跟踪http流

抓包时的log：

oriole:/data/local/tmp # ./ecapture tls -i wlan0 -w 11.pcapng                                                                                                                                                                              
tls_2022/10/13 13:28:40 ECAPTURE :: version :androidgki_aarch64:0.4.5-20221010-5019952:5.13.0-51-generic
tls_2022/10/13 13:28:40 ECAPTURE :: pid info :9377
tls_2022/10/13 13:28:40 EBPFProbeOPENSSL        module initialization
tls_2022/10/13 13:28:40 EBPFProbeOPENSSL        Module.Run()
tls_2022/10/13 13:28:40 EBPFProbeOPENSSL        TC MODEL
tls_2022/10/13 13:28:40 EBPFProbeOPENSSL        HOOK type:2, binrayPath:/apex/com.android.conscrypt/lib64/libssl.so
tls_2022/10/13 13:28:40 EBPFProbeOPENSSL        Ifname:wlan0, Ifindex:47,  Port:443, Pcapng filepath:/data/local/tmp/11.pcapng
tls_2022/10/13 13:28:40 EBPFProbeOPENSSL        target all process. 
tls_2022/10/13 13:28:40 EBPFProbeOPENSSL        target all users. 
tls_2022/10/13 13:28:40 EBPFProbeOPENSSL        module started successfully.
tls_2022/10/13 13:28:40 EBPFProbeGNUTLS module initialization
tls_2022/10/13 13:28:40 EBPFProbeGNUTLS Module.Run()
tls_2022/10/13 13:28:40 EBPFProbeGNUTLS module run failed, [skip it]. error:tls(gnutls) module couldn't find binPath stat /apex/com.android.conscrypt/lib64/libgnutls: no such file or directory
tls_2022/10/13 13:28:40 EBPFProbeNSPR   module initialization
tls_2022/10/13 13:28:40 EBPFProbeNSPR   Module.Run()
tls_2022/10/13 13:28:40 EBPFProbeNSPR   module run failed, [skip it]. error:tls module couldn't find binPath stat /apex/com.android.conscrypt/lib64/libnspr4.so: no such file or directory 
tls_2022/10/13 13:28:40 EBPFProbeGoSSL  module [disabled].
tls_2022/10/13 13:28:40 ECAPTURE ::     start 1 modules
tls_2022/10/13 13:29:07 non-TLSv1.3 cipher suite in tls13_hkdf_expand, CipherId: 0, use SHA256 default.
tls_2022/10/13 13:29:07 TLS1_3_VERSION: save CLIENT_RANDOM 2515f5cfc821a10c23293ef94b10bcb136f76fad9c0b0488f620845d5f54d864 to file success, 778 bytes
tls_2022/10/13 13:29:09 non-TLSv1.3 cipher suite in tls13_hkdf_expand, CipherId: 0, use SHA256 default.
tls_2022/10/13 13:29:09 TLS1_3_VERSION: save CLIENT_RANDOM 046e7df47426cd5d946c230bd2608b5ca9ef39ee4287ba8d26685a3917f48f0d to file success, 778 bytes
tls_2022/10/13 13:29:12 non-TLSv1.3 cipher suite in tls13_hkdf_expand, CipherId: 0, use SHA256 default.
tls_2022/10/13 13:29:12 TLS1_3_VERSION: save CLIENT_RANDOM 8a886aeb6d689e52530f63fdc10bdf343bd5474bbc03d4fbfa789482e84154bb to file success, 778 bytes
tls_2022/10/13 13:29:53 non-TLSv1.3 cipher suite in tls13_hkdf_expand, CipherId: 0, use SHA256 default.
tls_2022/10/13 13:29:53 TLS1_3_VERSION: save CLIENT_RANDOM c4147be06bf76deaebdbe180852b124bd8fc249f497c1cea463e91a6355b2813 to file success, 778 bytes
tls_2022/10/13 13:29:53 TLS1_2_VERSION: save CLIENT_RANDOM 0000000000000000000000000000000000000000000000000000000000000000 to file success, 176 bytes
tls_2022/10/13 13:29:53 TLS1_2_VERSION: save CLIENT_RANDOM a3e9b82294085cf507e6dc2e145b6586ae440fbc25f6d648838687997a55111b to file success, 176 bytes
tls_2022/10/13 13:29:56 non-TLSv1.3 cipher suite in tls13_hkdf_expand, CipherId: 0, use SHA256 default.
tls_2022/10/13 13:29:56 TLS1_3_VERSION: save CLIENT_RANDOM 6690fe6f14c9960f01e3e3a1505bb6d20f44c20e9dd36208a75676b071564950 to file success, 778 bytes
tls_2022/10/13 13:29:56 non-TLSv1.3 cipher suite in tls13_hkdf_expand, CipherId: 0, use SHA256 default.
tls_2022/10/13 13:29:56 TLS1_3_VERSION: save CLIENT_RANDOM 104d18dce4dbd9dfd4358a7b773aded94b34f93f5decb39e6ef9627dbd0d216f to file success, 778 bytes
tls_2022/10/13 13:29:56 non-TLSv1.3 cipher suite in tls13_hkdf_expand, CipherId: 0, use SHA256 default.
tls_2022/10/13 13:29:56 TLS1_3_VERSION: save CLIENT_RANDOM 63c4da24187e49ffdba0193478a9a4e729f6d26cdb480068013974fd3a772822 to file success, 778 bytes
tls_2022/10/13 13:29:56 non-TLSv1.3 cipher suite in tls13_hkdf_expand, CipherId: 0, use SHA256 default.
tls_2022/10/13 13:29:56 TLS1_3_VERSION: save CLIENT_RANDOM 6aa949e3f8563fa77a2163fbaa4ad0c11c9bf55339f28e94670512276e6b6f23 to file success, 778 bytes
tls_2022/10/13 13:30:02 non-TLSv1.3 cipher suite in tls13_hkdf_expand, CipherId: 0, use SHA256 default.
tls_2022/10/13 13:30:02 TLS1_3_VERSION: save CLIENT_RANDOM ac6424d0ec2f84b26da15e0ae062f5beecdd170378aac902723652bbad5ed6b1 to file success, 778 bytes
tls_2022/10/13 13:30:03 TLS1_2_VERSION: save CLIENT_RANDOM 5fd53c4d6eb7bfffcddc2b7c9a861a8bfc3a9ea84e20552548166b33a9f15668 to file success, 176 bytes
tls_2022/10/13 13:30:03 TLS1_2_VERSION: save CLIENT_RANDOM 29d82104d95c7e35262d534729be41c8d3ab2cfe6bc7706a90b569e58fc252d4 to file success, 176 bytes
tls_2022/10/13 13:30:04 TLS1_2_VERSION: save CLIENT_RANDOM ac5fe9911b92f58dc425ae4f5794867d8db8c422366517c86e78ef7bdceb1027 to file success, 176 bytes
tls_2022/10/13 13:30:04 TLS1_2_VERSION: save CLIENT_RANDOM 3fca135d8ed9cfd63a35b24cbe9362056510978844abfeca1f7fefceb08d25f9 to file success, 176 bytes
tls_2022/10/13 13:30:05 TLS1_2_VERSION: save CLIENT_RANDOM 75257478d12ac24ee5089425ebdf631281612e8e8fc52f08184b20849c292b6b to file success, 176 bytes
tls_2022/10/13 13:30:05 TLS1_2_VERSION: save CLIENT_RANDOM 3c470274c579f761340e52e1dc7970c46572601a301a958f4f55ddf43370353a to file success, 176 bytes
tls_2022/10/13 13:30:05 TLS1_2_VERSION: save CLIENT_RANDOM 17d3d348d5a1ed997b9f2e1425161af370e88d60beb73e1a89b8ac3ec62cb4c6 to file success, 176 bytes
tls_2022/10/13 13:30:05 TLS1_2_VERSION: save CLIENT_RANDOM 91afefc5cd5d33624bac8d82a535e274670bbc188d2768a33a0b39f8796a99b0 to file success, 176 bytes
tls_2022/10/13 13:30:05 TLS1_2_VERSION: save CLIENT_RANDOM 1924d8ef1c016ef4b87c89c12f670a3c4d8d5bf9ef3a2105b2ace087fb9cc415 to file success, 176 bytes
tls_2022/10/13 13:30:08 non-TLSv1.3 cipher suite in tls13_hkdf_expand, CipherId: 0, use SHA256 default.
tls_2022/10/13 13:30:08 TLS1_3_VERSION: save CLIENT_RANDOM c86077b9d4b027a961305cc3362f5431511b88d42918db7e56c3f586604292a5 to file success, 778 bytes
tls_2022/10/13 13:30:08 non-TLSv1.3 cipher suite in tls13_hkdf_expand, CipherId: 0, use SHA256 default.
tls_2022/10/13 13:30:08 TLS1_3_VERSION: save CLIENT_RANDOM d2f39ffcf421cf4470274d9394a5b9089320fe0b29dfdf278aa2d0677ebff820 to file success, 778 bytes
tls_2022/10/13 13:30:11 non-TLSv1.3 cipher suite in tls13_hkdf_expand, CipherId: 0, use SHA256 default.
tls_2022/10/13 13:30:11 TLS1_3_VERSION: save CLIENT_RANDOM 9e9a2ce528861d3c2282fddf330dadadfcbc04f35b38d90b1f49931150ae6d1d to file success, 778 bytes
tls_2022/10/13 13:30:12 TLS1_2_VERSION: save CLIENT_RANDOM de229510a11b65f43e8417987fc38804007a2ea5edda12c8825f4c3328130c1d to file success, 176 bytes
tls_2022/10/13 13:30:12 TLS1_2_VERSION: save CLIENT_RANDOM 0e2fba66b516556c02b6c21145f9ff6d3b767a91a71e55db6b5e90ef370f4114 to file success, 176 bytes
tls_2022/10/13 13:30:12 TLS1_2_VERSION: save CLIENT_RANDOM 26775edb0cbe8f034595c29a4265830dd8089260afa1b9db67d2ea580f86e69c to file success, 176 bytes
tls_2022/10/13 13:30:12 non-TLSv1.3 cipher suite in tls13_hkdf_expand, CipherId: 0, use SHA256 default.
tls_2022/10/13 13:30:12 TLS1_3_VERSION: save CLIENT_RANDOM 3514a602119f530cbe5efd38f85dffa8a6dcadafcdc44b495eab345b05d5074e to file success, 778 bytes
tls_2022/10/13 13:30:17 non-TLSv1.3 cipher suite in tls13_hkdf_expand, CipherId: 0, use SHA256 default.
tls_2022/10/13 13:30:17 TLS1_3_VERSION: save CLIENT_RANDOM a10920408835e5b8b741199e4d2a19c245807a96fa55631abf158c094c4abf41 to file success, 778 bytes
tls_2022/10/13 13:30:20 non-TLSv1.3 cipher suite in tls13_hkdf_expand, CipherId: 0, use SHA256 default.
tls_2022/10/13 13:30:20 TLS1_3_VERSION: save CLIENT_RANDOM fae360fa901baba67dc8da71e7f2d06c3e01ad5a607eb7f6da17c3bbf47331ee to file success, 778 bytes
tls_2022/10/13 13:30:42 non-TLSv1.3 cipher suite in tls13_hkdf_expand, CipherId: 0, use SHA256 default.
tls_2022/10/13 13:30:42 TLS1_3_VERSION: save CLIENT_RANDOM 34333a242d892c2e5bde4ec30858fe06f002aaed81df7310f8c4b0b79fca4cf4 to file success, 778 bytes
^Ctls_2022/10/13 13:30:49 EBPFProbeOPENSSL      saving pcapng file /data/local/tmp/11.pcapng
tls_2022/10/13 13:30:49 EBPFProbeOPENSSL         save 29514 packets into pcapng file.
tls_2022/10/13 13:30:49 EBPFProbeOPENSSL        close. 
tls_2022/10/13 13:30:49 EBPFProbeOPENSSL        close

**抓包的结果上传到了：

https://wwt.lanzouv.com/iBQij0dtbqdi**

**Comment by bluegatar** [comment]
补充：

 ./ecapture tls --uid=10224 -p 443

这样进行包过滤还是不行，没有输出

**Comment by cfc4n** [comment]
fixed at https://github.com/ehids/ecapture/pull/238

please retry [v0.4.6](https://github.com/ehids/ecapture/releases/tag/v0.4.6)

**Comment by cfc4n** [comment]
ping ?
