### ISSUE TITLE
kernal版本限制是不是必须？

### ISSUE THREAD

**Issue by jr981008** [ehids/ecapture#252]
android 10 对应内核4.14  
但是android apiversion >28 之后x86就不让用arm image了
导致x86 pc使用模拟器不可以抓包，ecapture x86在x86安卓镜像上不能使用
确认下 内核限制为4.15 是必须条件吗，还是可以放松到4.14 修改代码中限制即可？

**Comment by cfc4n** [comment]
> android 10 对应内核4.14 但是android apiversion >28 之后x86就不让用arm image了 导致x86 pc使用模拟器不可以抓包，ecapture x86在x86安卓镜像上不能使用 确认下 内核限制为4.15 是必须条件吗，还是可以放松到4.14 修改代码中限制即可？

Android模拟器X86架构的话，理论可以在4.14上使用，我没试过。 ARM架构不行，内核有bug。

**Comment by jr981008** [comment]
![image](https://user-images.githubusercontent.com/20749545/199172495-c97c6c94-3438-496b-9037-169098ab6581.png)

arndroid x86镜像直接使用 会报错  找不到/user/lib/libsssl.so 
需要修改什么参数吗？
还是需要ecapture 支持x86 android 要改ecapture代码？

**Comment by cfc4n** [comment]
eh, you are right , command `ecapture tls -w save_android.pcapng -i wlan0 --libssl=/apex/com.android.conscrypt/lib64/libssl.so --ssl_version="boringssl 1.1.1" --port 443` can works. try it.

will many user use `x86 android` ?

**Comment by jr981008** [comment]
The android virtual machine is used for app analysis on the x86 pc platform. The android native image is not allowed to run the arm image on the x86 platform after 28,its common scenario.

**Comment by cfc4n** [comment]
> The android virtual machine is used for app analysis on the x86 pc platform. The android native image is not allowed to run the arm image on the x86 platform after 28,its common scenario.

but can app supported x86_64 Android ? like `Wechat`、`Alipay` ,  I think that apps support x86_64  android less and less.

**Comment by jr981008** [comment]
If adding compilation parameters or process argument can solve the problem, I think it can be done just through a document. If it is more complicated, I suggest that it is best to have a realse package. My scenario is to analyze some protocols of the android ecosystem, such as some moblie service

**Comment by cfc4n** [comment]
> 

on x86_64 Linux ,compile Android version:
```shell
ANDROID=1 make
# or
ANDROID=1 make nocore
```

**Comment by cfc4n** [comment]
@jr981008  try  [v0.4.8](https://github.com/ehids/ecapture/releases/tag/v0.4.8) please.
