### ISSUE TITLE
使用“-w”dump出的pcapng包没有明文显示

### ISSUE THREAD

**Issue by robbietu** [ehids/ecapture#254]
**运行环境**
centos 8.2
kernel版本  4.18.0-193.el8.x86_64

**问题及复现步骤**
1. 执行 “./ecapture tls”
2. 在服务器上面执行 curl hittps://www.baidu.com
3. 可以看到有明文的https消息打印
![1](https://user-images.githubusercontent.com/77134559/199144654-287904e8-b747-43ec-85bc-995ab0571c97.jpg)
4.改用pcapng dump方式，命令改为 “ ./ecapture tls -i ens192 -w 1.pcapng --libssl="/lib64/libssl.so.1.1"，pcapng包里的消息并没有明文显示
![2](https://user-images.githubusercontent.com/77134559/199145321-51c045dd-a00d-4eb6-ae88-96baa81d3298.jpg)
![3](https://user-images.githubusercontent.com/77134559/199145348-8330db87-281f-45ce-9dee-cd7c24ecf249.jpg)

另外还尝试了--libssl=“/lib64/libssl.so.1.1.1c” ,--libssl=“/usr/lib64/libssl.so.1.1.1c”以及--libssl=“/usr/lib64/libssl.so.1.1”，依然无法获得明文的pcapng包。这些都是libssl.so的软链接

**附curl的ldd结果**
![4](https://user-images.githubusercontent.com/77134559/199145783-a8610ba0-2891-4383-b2bb-2e8e98136bbb.jpg)

请帮忙看看是什么问题，多谢！！

**Comment by cfc4n** [comment]
use `./ecapture tls -i ens192 -w 1.pcapng --libssl="/lib64/libssl.so.1.1" --ssl_version="openssl 1.1.1c"` instead .

it is a bug fixed at #250 , will release new version next weekend.

**Comment by robbietu** [comment]
用这个命令就可以了
