### ISSUE TITLE
Is it possible to work on Android OS?

### ISSUE THREAD

**Issue by fei-ke** [ehids/ecapture#26]
I see that Android supports [eBPF](https://source.android.com/devices/architecture/kernel/bpf), Is it possible we can make this project work on Android with the help of tools like Magisk/Zygisk.

**Comment by cfc4n** [comment]
as you know ,Android is support eBPF. may be it will work. you can try it.  like:https://github.com/ehids/slide/blob/master/android/eBPF-super-powers-on-ARM64-and-android.pdf
