### ISSUE TITLE
Collaborate with other network protocol analyzers/generate SSLKEYLOGFILE

### ISSUE THREAD

**Issue by robberphex** [ehids/ecapture#27]
*Thank you, ecapture is a great tool for tls capture.*

Currently, ecapture cannot use other network analyzer, i.e. Wireshark. ecapture may support generate `SSLKEYLOGFILE` and pcap file, which can be analyzed by [Wireshark](https://wiki.wireshark.org/TLS#using-the-pre-master-secret).

P.S. [NSS Key Log Format](https://firefox-source-docs.mozilla.org/security/nss/legacy/key_log_format/index.html)

P.S. [Keylog could embed into pcapng file](https://wiki.wireshark.org/TLS#embedding-decryption-secrets-in-a-pcapng-file)

**Comment by cfc4n** [comment]
I thought about this feature.

Runtime data is missing a lot of IP protocol stack data, and it is difficult to got target network layer and runtime data.

Do you have any good idea?

**Comment by cfc4n** [comment]
ref : https://security.stackexchange.com/questions/80158/extract-pre-master-keys-from-an-openssl-application

**Comment by mosajjal** [comment]
I'd be keen to have a stab at this at some point and leverage `ecapture` to further enhance my pet project [tcpshark](//github.com/mosajjal/tcpshark)

**Comment by cfc4n** [comment]
> I'd be keen to have a stab at this at some point and leverage `ecapture` to further enhance my pet project [tcpshark](//github.com/mosajjal/tcpshark)

Waiting for good news.

**Comment by Ubbo-Sathla** [comment]
好人一生平安

**Comment by robberphex** [comment]
DSB(Decryption Secrets Block) works perfectly! Thanks!
![image](https://user-images.githubusercontent.com/1926185/183325534-e2fb6a1f-4e80-41b5-985f-0b090f4b9652.png)
