### ISSUE TITLE
release no core version 安卓

### ISSUE THREAD

**Issue by Zxilly** [ehids/ecapture#277]
## Env:
Android Kernel: 4.19.157-perf-g42d3bfdbbffc
ecapture version: https://github.com/ehids/ecapture/releases/download/v0.4.9/ecapture-v0.4.9-android-aarch64-nocore.tar.gz

## Log
<details>
<pre lang="log" class="notranslate"><code>thyme:/data/local/tmp # ./ecapture tls
tls_2022/11/26 12:05:25 ECAPTURE :: ecapture Version : androidgki_aarch64:0.4.9-20221119-dcc7142:5.4.0-104-generic
tls_2022/11/26 12:05:25 ECAPTURE :: Pid Info : 25379
tls_2022/11/26 12:05:25 ECAPTURE :: Kernel Info : 4.19.157
tls_2022/11/26 12:05:25 EBPFProbeOPENSSL        module initialization
tls_2022/11/26 12:05:25 EBPFProbeOPENSSL        master key keylogger: ecapture_masterkey.log
tls_2022/11/26 12:05:25 EBPFProbeOPENSSL        Module.Run()
tls_2022/11/26 12:05:25 EBPFProbeOPENSSL        UPROBE MODEL
tls_2022/11/26 12:05:25 EBPFProbeOPENSSL        OpenSSL/BoringSSL version not found, used default version :android_default
tls_2022/11/26 12:05:25 EBPFProbeOPENSSL        HOOK type:2, binrayPath:/apex/com.android.conscrypt/lib64/libssl.so
tls_2022/11/26 12:05:25 EBPFProbeOPENSSL        libPthread so Path:/apex/com.android.runtime/lib64/bionic/libc.so
tls_2022/11/26 12:05:25 EBPFProbeOPENSSL        BPF bytecode filename:user/bytecode/boringssl_1_1_1_kern_less52.o
tls_2022/11/26 12:05:25 EBPFProbeOPENSSL        module run failed, [skip it]. error:couldn't init manager error:map skb_data_buffer_heap: load BTF: detect support for BTF: no such file or directory , couldn't load eBPF programs, cs:&amp;{map[active_ssl_read_args_map:Hash(keySize=8, valueSize=16, maxEntries=1024, flags=0) active_ssl_write_args_map:Hash(keySize=8, valueSize=16, maxEntries=1024, flags=0) bpf_context:LRUHash(keySize=8, valueSize=408, maxEntries=2048, flags=0) bpf_context_gen:Array(keySize=4, valueSize=408, maxEntries=1, flags=0) connect_events:PerfEventArray(keySize=0, valueSize=0, maxEntries=0, flags=0) data_buffer_heap:PerCPUArray(keySize=4, valueSize=4152, maxEntries=1, flags=0) mastersecret_events:PerfEventArray(keySize=0, valueSize=0, maxEntries=0, flags=0) skb_data_buffer_heap:PerCPUArray(keySize=4, valueSize=40, maxEntries=1, flags=0) skb_events:PerfEventArray(keySize=0, valueSize=0, maxEntries=8, flags=0) tls_events:PerfEventArray(keySize=0, valueSize=0, maxEntries=0, flags=0)] map[egress_cls_func:0x40000afb80 ingress_cls_func:0x40000afc20 probe_connect:0x40000afa40 probe_entry_SSL_read:0x40000af7c0 probe_entry_SSL_write:0x40000afcc0 probe_ret_SSL_read:0x40000af9a0 probe_ret_SSL_write:0x40000af900 probe_ssl_master_key:0x40000afae0] 0x4000096e40 LittleEndian}
tls_2022/11/26 12:05:25 ECAPTURE ::     No runnable modules, Exit(1)
</code></pre>
</details>

**Comment by cfc4n** [comment]
eCapture does not support kernel version less than 5.4 with ARM64/aarch64 arch.
