### ISSUE TITLE
does not support NSS

### ISSUE THREAD

**Issue by shareinto** [ehids/ecapture#3]
`curl --version
curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.53.1 zlib/1.2.7 libidn/1.28 libssh2/1.8.0
`
`ldd /usr/bin/curl | grep ssl
        libssl3.so => /usr/lib64/libssl3.so (0x00007f255286b000)
        libssl.so.10 => /usr/lib64/libssl.so.10 (0x00007f254f9e4000)`

libssl3.so is NSS , it does not contain SSL_read/SSL_write function

**Comment by cfc4n** [comment]
supported at v0.1.5 as nspr flag.
