### ISSUE TITLE
[feat] support postgres

### ISSUE THREAD

**Issue by yihong0618** [ehids/ecapture#48]
Maybe we can support `postgres` (version 11+) like `mysql` 

I think I can open a `PR` to support this. 
but I am not sure we can get the `return value` like #44  will take a try.

**Comment by cfc4n** [comment]
of course.  you can add this feature with a new PR like 
https://github.com/ehids/ecapture/blob/656a3a5939f8df05a9dc915a18007283c34127cc/kern/mysqld_kern.c#L155-L158

and ref https://github.com/mysql/mysql-server/blob/c94ce787737f9a6c9a31abe22bee02866698885b/sql/sql_parse.h#L93
