### ISSUE TITLE
无法编译

### ISSUE THREAD

**Issue by Top-Fish** [ehids/ecapture#59]
我的编译结果如下：
root@ubantu:/home/disk/workspace/ecapture# make
clang -D__TARGET_ARCH_x86 \
        -O2 -mcpu=v1 -nostdinc -Wno-pointer-sign \
        -I./kern  \
        -target bpfel -c kern/openssl_kern.c -o user/bytecode/openssl_kern.o \
        -fno-ident -fdebug-compilation-dir . -g -D__BPF_TARGET_MISSING="GCC error \"The eBPF is using target specific macros, please provide -target\"" \
        -MD -MP
clang: error: unknown argument: '-fdebug-compilation-dir'
clang: warning: .: 'linker' input unused [-Wunused-command-line-argument]
Makefile:62: recipe for target 'kern/openssl_kern.o' failed
make: *** [kern/openssl_kern.o] Error 1

配置如下：
ubantu 1804
golang 1.18
clang 6.0
pahole 1.21
cmake 3.10

**Comment by cfc4n** [comment]
clang版本太低了，详细软件版本参考说明。

**Comment by Top-Fish** [comment]
> clang版本太低了，详细软件版本参考说明。

多谢，我再试试

**Comment by cfc4n** [comment]
先关闭了，有问题再重开。
