### ISSUE TITLE
OpenWRT does not work

### ISSUE THREAD

**Issue by ettwz** [ehids/ecapture#64]
![image](https://user-images.githubusercontent.com/20449556/170818741-34fa413b-9027-4985-bd1e-9a548b887e00.png)

![image](https://user-images.githubusercontent.com/20449556/170818899-05b0f826-69bd-42cf-bb9a-14237966f17d.png)

![image](https://user-images.githubusercontent.com/20449556/170827567-ea6c2840-39ae-4aac-a618-897c88b2f488.png)

Already selected `libbpf` when compiling the system.
How can I get more debug message?

Thanks.

**Comment by cfc4n** [comment]
can you give more detail like https://github.com/ehids/ecapture/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by ettwz** [comment]
**Describe the bug**
get npe when ecapture start

**To Reproduce**
Steps to reproduce the behavior:
1. wget https://github.com/ehids/ecapture/releases/download/v0.1.8/ecapture-v0.1.8.tar.gz
2. tar -xzvf ecapture-v0.1.8.tar.gz
3. mv bin/ecapture /usr/bin/
4. ecapture -h
5. See error

**Expected behavior**
get more debug message

**Screenshots**
![image](https://user-images.githubusercontent.com/20449556/170851817-afad66c9-f423-4c81-bd58-ccefa704f045.png)

**Linux Server/Desktop (please complete the following information):**
 - OS: [OpenWRT]
 - Kernel Version [5.15.41]
 - Version [OpenWrt SNAPSHOT, r4532-95b3b801e]

**Additional context**
/usr/lib/libbpf.so.0 -> /usr/lib/libbpf.so.0.3.0*

**Comment by cfc4n** [comment]
Sorry, I don't have an OpenWRT runtime environment to debug this issue.

But ,My guess is that you intend to use openwrt to capture network packets. But this can only be used at runtime, it will not work on link layer.

**Comment by ettwz** [comment]
Alright
