### ISSUE TITLE
 bash的命令捕获功能，可以捕获执行完命令后的输出结果吗？

### ISSUE THREAD

**Issue by yueyongyue** [ehids/ecapture#66]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Linux Server/Desktop (please complete the following information):**
 - Kernel Version [e.g. 5.10]
 - Version [e.g. 0.1.3-20220313-69c1e0]

**Additional context**

**Comment by cfc4n** [comment]
命令执行的状态（是否成功，状态值）是有的。但标准输出就没必要去捕获了，因为内容可能特别多，不太好控制。

或者，你说一下你的场景，让我评估一下这个需求。

**Comment by yueyongyue** [comment]
暂时也没有什么特别的需求，就是想丰富一下功能，或者说这个输出结果我用ebpf应该怎么捕获到，应该probe什么，比较迷茫

**Comment by cfc4n** [comment]
嗯，我近期写一篇入门的文章吧，如何确定probe HOOK函数，如何简单使用ebpf。
