### ISSUE TITLE
The output can be with pcap format?

### ISSUE THREAD

**Issue by BurlyLuo** [ehids/ecapture#67]
**Describe the bug**
Can we have a possible to export the outputs with pcap format?
**To Reproduce**

**Expected behavior**

**Screenshots**

**Linux Server/Desktop (please complete the following information):**
 - Kernel Version [e.g. 5.10]
 - Version [e.g. 0.1.3-20220313-69c1e0]

**Additional context**

**Comment by BurlyLuo** [comment]
Maybe it can not be achieved due to the work layer.

**Comment by cfc4n** [comment]
yes, eCapture works at runtime,not link layer.  some fields cant capture about network.
