### ISSUE TITLE
很抱歉，我水一下

### ISSUE THREAD

**Issue by yundmb** [ehids/ecapture#96]
大佬！牛逼！！！

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Linux Server/Android (please complete the following information):**

- OS: [e.g. Ubuntu 21.04]
- Arch: [e.g. arm_aarch64]
- Kernel Version: [e.g. 5.10]
- Version: [e.g. 0.1.3-20220313-69c1e0]

**Additional context**

**Comment by yundmb** [comment]
各位，很抱歉，我知道这样做不对，但是大佬，牛逼！

**Comment by yihong0618** [comment]
这种水一下的，GitHub 专门有个 discussion 哈哈。

**Comment by cfc4n** [comment]
也可以到QQ群里水。。 在「榫卯江湖」微信公众号的菜单里有群二维码。
